### PR TITLE
Add autoEnd option

### PR DESCRIPTION
**Pull request by xdcarter**
add option autoEnd to match the raw API pipe from Stream in NodeJS. This option enable append some customized data to the raw file。It make easy to implement BigPipe like function。it also help to add some hook code to handle JS module dependence when downloading JS file async in Dev mode。

### CODE REVIEW

**Comment by dougwilson** [comment]
Hi @xdcarter why are you closing and re-opening this PR over and over? It looks identical to https://github.com/pillarjs/send/pull/135 which you closed. Are you trying to change some aspect of the PR? I'm not sure how to proceed here, or what I need to wait for from you to change.

**Comment by xdcarter** [comment]
sorry, I'm fresh at github，I do need to familiar with flow。I used to create new pr at gitlab in my local office

**Comment by dougwilson** [comment]
I can understand that, but it's identical to #135 . Are you trying to change some aspect of the PR? I'm not sure how to proceed here, or what I need to wait for from you to change.

**Comment by xdcarter** [comment]
would just forget the #135 #136？

**Comment by xdcarter** [comment]
Sorry for the confusion caused. Yes, you're right that the previous PR is same with #137. For now, I have nothing to change. Pls go on reviewing my merge request.

**Comment by dougwilson** [comment]
Please make the changes requested in https://github.com/pillarjs/send/pull/135#issuecomment-284196043

**Comment by dougwilson** [comment]
I never heard back and the source repository is gone, which makes it un-mergeable.

**Pull request closed without merging**
