### PR TITLE
Release 1.0

### PR DESCRIPTION
**Pull request by dougwilson**
This is a tracking issue for release 1.0.

I am trying to give better visibility for upcoming changes and so am trying out making a PR for a release here, pulling from the official next release branch into `master`. This allows for the current pending changes to be easily visible.

**Please keep feature requests in their own issues**

I'm also leaving this PR unlocked so people can make comments/etc. and we'll see how it goes :) If you want to make a comment on a particular change, please make the comment in the "Files changed" tab so comments are not lost during a rebase.

List of changes for release:
- [x] Use `mime-types` instead of `mime` #192

List of deprecated things removed:
- [x] `send.etag()`
- [x] `send.hidden()` and `hidden` option
- [x] `send.index()`
- [x] `send.maxage()`
- [x] `send.root()`

**Testing this release**

If you want to try out this release, you can install it with the following command:

``` bash
$ npm install pillarjs/send#1.0
```

Owners/collaborators: please do not merge this PR :)

### CODE REVIEW

**Comment by hello-smile6** [comment]
Will this break some packages?

**Comment by dougwilson** [comment]
Hi @hello-smile6 it may, depending on what they are using. The included change log (`History.md`) details the changes. This is why it is a major version. There will be a beta.1 release tonight so folks can test and provide feedback.

**Comment by hello-smile6** [comment]
> Hi @hello-smile6 it may, depending on what they are using. The included change log (`History.md`) details the changes. This is why it is a major version. There will be a beta.1 release tonight so folks can test and provide feedback.

Okay. I was just checking, because some people mindlessly do major version updates. Could you show an error explaining that the functions you've removed were removed and listing the most recent version with features for the features that have been removed, rather than just removing them?

**Comment by dougwilson** [comment]
Hi @hello-smile6 if you are using any of the removed functionality in the current version, you will already see a warning.

**Comment by hello-smile6** [comment]
> Hi @hello-smile6 if you are using any of the functionality that is bring here, in the current version you will already see a warning.

Oh, that's a relief. I actually didn't realize that this library was used in expressjs at one point and asked for it to work better with expressjs, which shows why people would be extremely confused if features were removed in a minor version.

**Comment by SukkaW** [comment]
Hello. Thanks for the great work!

I'd like to know when will `send@1.0.0` would be landed. The PR has been stale for 7 months, are there any blocking issues?

**Comment by wesleytodd** [comment]
@pillarjs/express-tc could I get a few eyes on this? I bumped a bunch of deps to latest, changed over to `^` ranges so we dont have as much work to do on this in the future, but otherwise this is older changes. If I can get an approval just double checking this I will publish the 1.0 and then update `express@5` to use it and mark it off on https://github.com/expressjs/discussions/issues/233

**Comment by wesleytodd** [comment]
I published `1.0.0` on the `next` dist tag, we can bump that to `latest` when we are ready to handle any support issues for that. Since I was unable to get more validation on this than just bumping it in express I went with that here https://github.com/expressjs/express/pull/5786.

**Pull request merged**
