### PR TITLE
Update README.md

### LINKED ISSUE #103: Documented start/end options
I wanted to serve only parts of a large file and found the undocumented start/end options to serve exactly this purpose. E.g. I have a large audio file and only want to stream a short extract of which I know the start and end bytes. So I call `/large.mp3?start=1234&end=5678` and pass the query parameters as options to send and I get exactly what I want.
The start and end options are not documented though, therefore I would like to know if this is just missing documentation, or if they are internal properties and setting them might break other features, e.g. conditional-GET etc.

### PR DESCRIPTION
**Pull request by mh-cbon**
fix #103

### CODE REVIEW

**Comment by tunniclm** [comment]
Nice

**Comment by mh-cbon** [comment]
much better indeed

**Comment by maenu** [comment]
Sweet! Thanks guys.

**Comment by dougwilson** [comment]
No problem, @maenu! @mh-cbon jumped right in there and helped you out :) I hope having it documented makes you feel more comfortable about using it :)

**Comment by maenu** [comment]
It absolutely makes me feel more comfortable to have documentation about the features I am using. This makes sure that I am not programming against an implementation detail but a published contract one can put the finger on, should the documentation not be reflected in the runtime behaviour.

**Comment by mh-cbon** [comment]
just needed to be done for everyone : s cool it s done :  )

**Pull request closed without merging**
